SEVERITY_NORMAL = "NORMAL"

SEVERITY_LOW = "LOW"

SEVERITY_MODERATE = "MODERATE"

SEVERITY_HIGH = "HIGH"

SEVERITY_CRITICAL = "CRITICAL"


TREND_IMPROVING = "IMPROVING"

TREND_WORSENING = "WORSENING"

TREND_STABLE = "STABLE"

TREND_UNKNOWN = "UNKNOWN"


CATEGORY_RENAL = "RENAL"

CATEGORY_ENDOCRINE = "ENDOCRINE"

CATEGORY_HEMATOLOGY = "HEMATOLOGY"

CATEGORY_LIVER = "LIVER"

CATEGORY_CARDIAC = "CARDIAC"

CATEGORY_INFECTION = "INFECTION"

CATEGORY_ONCOLOGY = "ONCOLOGY"

CATEGORY_ELECTROLYTE = "ELECTROLYTE"